# example input configuration file for the cli tool xil-vcdl-generator.exe
version: "2.0.0"
general-settings:
    root-namespace-name: "XILServer"
testbench:
    vendor-name: "Example Vendor"
    product-name: "Example Product"
    xil-version: "2.1.0"
    implementation-manifest-folder: "XILAPIConfiguration"
    runtime-implementation-manifest-folder: "XILAPIConfiguration"
ma-port:
    config-file-path: "XILAPIConfiguration/VendorMAPortConfig.xml"
    runtime-config-file-path: "XILAPIConfiguration/VendorMAPortConfig.xml"
variables:
# use wildcard regex to apply format for all variables
    - filter: "."
      format: "%n/%o.%m"
