#!/usr/bin/env python3
"""Build document fill template from doc binding bundle.

Input:
- doc_binding_bundle.csv (from build_doc_binding_bundle.py)

Output:
- doc_fill_template.csv
- doc_fill_template.md
"""

from __future__ import annotations

import argparse
import csv
import datetime as dt
from collections import Counter, defaultdict
from pathlib import Path


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Build 05/06/07 fill template from doc binding CSV")
    parser.add_argument(
        "--binding-csv",
        type=Path,
        default=Path("canoe/tmp/reports/verification/doc_binding_bundle.csv"),
        help="Input binding CSV generated by verify bind-doc",
    )
    parser.add_argument("--run-id", default="", help="Optional run id for report context")
    parser.add_argument("--owner-fallback", default="TBD", help="Owner fallback for READY rows")
    parser.add_argument("--date-fallback", default=dt.date.today().isoformat(), help="Date fallback for READY rows")
    parser.add_argument(
        "--output-csv",
        type=Path,
        default=Path("canoe/tmp/reports/verification/doc_fill_template.csv"),
    )
    parser.add_argument(
        "--output-md",
        type=Path,
        default=Path("canoe/tmp/reports/verification/doc_fill_template.md"),
    )
    return parser


def load_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"binding csv not found: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def to_pass_fail(binding_status: str, computed_verdict: str) -> str:
    if binding_status != "READY":
        return ""
    verdict = (computed_verdict or "").strip().upper()
    if verdict in {"PASS", "FAIL"}:
        return verdict
    return ""


def to_action(binding_status: str) -> str:
    if binding_status == "READY":
        return "APPLY_TO_DOC"
    if binding_status == "DOC_ONLY":
        return "RUN_AND_SCORE_REQUIRED"
    if binding_status == "EVIDENCE_ONLY":
        return "ADD_DOC_ID_OR_RENAME_TEST"
    return "REVIEW_REQUIRED"


def main() -> int:
    args = build_parser().parse_args()
    rows = load_rows(args.binding_csv)
    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    out_rows: list[dict[str, str]] = []
    by_status = Counter()
    by_doc = Counter()
    by_pass_fail = Counter()
    pending_by_doc: dict[str, list[str]] = defaultdict(list)

    for row in rows:
        binding_status = (row.get("binding_status") or "").strip()
        test_id = (row.get("test_id") or "").strip()
        doc_file = (row.get("doc_file") or "").strip()
        computed_verdict = (row.get("computed_verdict") or "").strip()
        owner = (row.get("owner") or "").strip()
        run_date = (row.get("run_date") or "").strip()

        pass_fail = to_pass_fail(binding_status, computed_verdict)
        action_required = to_action(binding_status)

        if binding_status == "READY":
            owner = owner or args.owner_fallback
            run_date = run_date or args.date_fallback
        else:
            owner = ""
            run_date = ""

        out = {
            "tier": (row.get("tier") or "").strip(),
            "doc_file": doc_file,
            "test_id": test_id,
            "pass_fail": pass_fail,
            "owner": owner,
            "run_date": run_date,
            "computed_verdict": computed_verdict,
            "computed_latency_ms": (row.get("computed_latency_ms") or "").strip(),
            "rule_ms": (row.get("rule_ms") or "").strip(),
            "evidence_log_path": (row.get("evidence_log_path") or "").strip(),
            "evidence_capture_path": (row.get("evidence_capture_path") or "").strip(),
            "computed_fail_reasons": (row.get("computed_fail_reasons") or "").strip(),
            "binding_status": binding_status,
            "action_required": action_required,
            "note": (row.get("note") or "").strip(),
        }
        out_rows.append(out)

        by_status[binding_status] += 1
        by_doc[doc_file] += 1
        if pass_fail:
            by_pass_fail[pass_fail] += 1
        if action_required != "APPLY_TO_DOC":
            pending_by_doc[doc_file].append(test_id)

    out_rows.sort(key=lambda r: (r["doc_file"], r["tier"], r["binding_status"], r["test_id"]))

    args.output_csv.parent.mkdir(parents=True, exist_ok=True)
    args.output_md.parent.mkdir(parents=True, exist_ok=True)

    fields = [
        "tier",
        "doc_file",
        "test_id",
        "pass_fail",
        "owner",
        "run_date",
        "computed_verdict",
        "computed_latency_ms",
        "rule_ms",
        "evidence_log_path",
        "evidence_capture_path",
        "computed_fail_reasons",
        "binding_status",
        "action_required",
        "note",
    ]
    with args.output_csv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=fields)
        writer.writeheader()
        writer.writerows(out_rows)

    lines = [
        "# 05/06/07 Fill Template Report",
        "",
        f"- Generated: {now}",
        f"- Run ID: `{args.run_id or 'N/A'}`",
        f"- Binding CSV: `{args.binding_csv}`",
        f"- Rows: {len(out_rows)}",
        "",
        "## Status Summary",
        f"- READY: {by_status['READY']}",
        f"- DOC_ONLY: {by_status['DOC_ONLY']}",
        f"- EVIDENCE_ONLY: {by_status['EVIDENCE_ONLY']}",
        "",
        "## Verdict Summary (READY rows)",
        f"- PASS: {by_pass_fail['PASS']}",
        f"- FAIL: {by_pass_fail['FAIL']}",
        "",
        "## By Document",
    ]
    for doc_file in sorted(k for k in by_doc.keys() if k):
        lines.append(f"- {doc_file}: {by_doc[doc_file]} rows")

    lines += [
        "",
        "## Pending Actions (Top 20 IDs per doc)",
    ]
    for doc_file in sorted(k for k in pending_by_doc.keys() if k):
        preview = ", ".join(pending_by_doc[doc_file][:20]) or "-"
        lines.append(f"- {doc_file}: {preview}")

    lines += [
        "",
        "## Output",
        f"- CSV: `{args.output_csv}`",
        f"- MD: `{args.output_md}`",
    ]
    args.output_md.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(
        f"[DOC_FILL] rows={len(out_rows)} ready={by_status['READY']} "
        f"doc_only={by_status['DOC_ONLY']} evidence_only={by_status['EVIDENCE_ONLY']}"
    )
    print(f"[OUT] {args.output_csv}")
    print(f"[OUT] {args.output_md}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
