; MATLAB version: 9.5.0.1298439 (R2018b) Update 7
; Vector CANoe MATLAB Integration Package version: 8.1.3

[Model]
MATLABVersion=9.5
Name=model2
GraphicsFormat=emf
Optimization=0
INIFileVersion=2.2
NumberOfBlocks=4
SystemLeft=250
SystemTop=288
SystemRight=706
SystemBottom=323
GraphicFileName=model2.emf

[model2_1]
Path= Base Workspace
Name=Base Workspace
Description=Global MATLAB base workspace
Typ=Workspace
NumberOfParameters=0

[model2_2]
Path=model2 Model Workspace
Name=Model Workspace
Description=model2 workspace
Typ=Workspace
NumberOfParameters=0

[model2_3]
Path=model2/System Variable Input
Name=System Variable Input
Description=
Left=260
Top=285
Right=310
Bottom=315
MaskType=System Variable Input Module
NumberOfParameters=9
Parameter_Name_1=nsName
Parameter_Value_1=Ert
Parameter_Name_2=sysVarName
Parameter_Value_2=InputModel2
Parameter_Name_3=arrayIndex
Parameter_Value_3=-1
Parameter_Name_4=editSampleTime
Parameter_Value_4=0
Parameter_Name_5=rawValue
Parameter_Value_5=Default
Parameter_Name_6=dataType
Parameter_Value_6=Default
Parameter_Name_7=dataTypeDB
Parameter_Value_7=unknown
Parameter_Name_8=hasEncoding
Parameter_Value_8=off
Parameter_Name_9=dataTypeCANoe
Parameter_Value_9=Get from CANoe
NumberOfInputSignals=0
NumberOfOutputSignals=1
NumberOfBlocks=0

[model2_4]
Path=model2/System Variable Output
Name=System Variable Output
Description=
Left=635
Top=285
Right=685
Bottom=315
MaskType=System Variable Output Module
NumberOfParameters=8
Parameter_Name_1=nsName
Parameter_Value_1=Ert
Parameter_Name_2=sysVarName
Parameter_Value_2=SysvarSineModified
Parameter_Name_3=arrayIndex
Parameter_Value_3=-1
Parameter_Name_4=rawValue
Parameter_Value_4=Default
Parameter_Name_5=dataType
Parameter_Value_5=Default
Parameter_Name_6=dataTypeDB
Parameter_Value_6=unknown
Parameter_Name_7=hasEncoding
Parameter_Value_7=off
Parameter_Name_8=dataTypeCANoe
Parameter_Value_8=Get from CANoe
NumberOfInputSignals=1
NumberOfOutputSignals=0
NumberOfBlocks=0

