; MATLAB version: 9.5.0.1298439 (R2018b) Update 7
; Vector CANoe MATLAB Integration Package version: 8.1.3

[Model]
MATLABVersion=9.5
Name=RtkModel
GraphicsFormat=emf
Optimization=0
INIFileVersion=2.2
NumberOfBlocks=4
SystemLeft=98
SystemTop=178
SystemRight=272
SystemBottom=213
GraphicFileName=RtkModel.emf

[RtkModel_1]
Path= Base Workspace
Name=Base Workspace
Description=Global MATLAB base workspace
Typ=Workspace
NumberOfParameters=0

[RtkModel_2]
Path=RtkModel Model Workspace
Name=Model Workspace
Description=RtkModel workspace
Typ=Workspace
NumberOfParameters=0

[RtkModel_3]
Path=RtkModel/Sine Wave
Name=Sine Wave
Description=
Left=95
Top=175
Right=125
Bottom=205
NumberOfParameters=10
Parameter_Name_1=SineType
Parameter_Value_1=Time based
Parameter_Name_2=TimeSource
Parameter_Value_2=Use simulation time
Parameter_Name_3=Amplitude
Parameter_Value_3=1
Parameter_Name_4=Bias
Parameter_Value_4=0
Parameter_Name_5=Frequency
Parameter_Value_5=1
Parameter_Name_6=Phase
Parameter_Value_6=0
Parameter_Name_7=Samples
Parameter_Value_7=10
Parameter_Name_8=Offset
Parameter_Value_8=0
Parameter_Name_9=SampleTime
Parameter_Value_9=0
Parameter_Name_10=VectorParams1D
Parameter_Value_10=on
NumberOfInputSignals=0
NumberOfOutputSignals=1
NumberOfBlocks=0

[RtkModel_4]
Path=RtkModel/System Variable Output
Name=System Variable Output
Description=
Left=220
Top=175
Right=270
Bottom=205
MaskType=System Variable Output Module
NumberOfParameters=8
Parameter_Name_1=nsName
Parameter_Value_1=Demo
Parameter_Name_2=sysVarName
Parameter_Value_2=RtkSine
Parameter_Name_3=arrayIndex
Parameter_Value_3=-1
Parameter_Name_4=rawValue
Parameter_Value_4=Default
Parameter_Name_5=dataType
Parameter_Value_5=Default
Parameter_Name_6=dataTypeDB
Parameter_Value_6=unknown
Parameter_Name_7=hasEncoding
Parameter_Value_7=off
Parameter_Name_8=dataTypeCANoe
Parameter_Value_8=Get from CANoe
NumberOfInputSignals=1
NumberOfOutputSignals=0
NumberOfBlocks=0

