; MATLAB version: 9.5.0.1298439 (R2018b) Update 7
; Vector CANoe MATLAB Integration Package version: 8.2.5

[Model]
MATLABVersion=9.5
Name=ErtSine
GraphicsFormat=emf
Optimization=0
INIFileVersion=2.2
NumberOfBlocks=4
SystemLeft=328
SystemTop=218
SystemRight=737
SystemBottom=253
GraphicFileName=ErtSine.emf

[ErtSine_1]
Path= Base Workspace
Name=Base Workspace
Description=Global MATLAB base workspace
Typ=Workspace
NumberOfParameters=0

[ErtSine_2]
Path=ErtSine Model Workspace
Name=Model Workspace
Description=ErtSine workspace
Typ=Workspace
NumberOfParameters=0

[ErtSine_3]
Path=ErtSine/Signal Output
Name=Signal Output
Description=
Left=695
Top=215
Right=745
Bottom=245
MaskType=Signal Output Module
NumberOfParameters=8
Parameter_Name_1=dbName
Parameter_Value_1=SimulinkDemo
Parameter_Name_2=nodeName
Parameter_Value_2=ErtNode
Parameter_Name_3=msgName
Parameter_Value_3=ErtSineMsg
Parameter_Name_4=sigName
Parameter_Value_4=SignalSine
Parameter_Name_5=rawValue
Parameter_Value_5=Raw value
Parameter_Name_6=dataType
Parameter_Value_6=double
Parameter_Name_7=dataTypeDB
Parameter_Value_7=unknown
Parameter_Name_8=hasEncoding
Parameter_Value_8=off
NumberOfInputSignals=1
NumberOfOutputSignals=0
NumberOfBlocks=0

[ErtSine_4]
Path=ErtSine/Sine Wave
Name=Sine Wave
Description=
Left=325
Top=215
Right=355
Bottom=245
NumberOfParameters=10
Parameter_Name_1=SineType
Parameter_Value_1=Time based
Parameter_Name_2=TimeSource
Parameter_Value_2=Use simulation time
Parameter_Name_3=Amplitude
Parameter_Value_3=1
Parameter_Name_4=Bias
Parameter_Value_4=0
Parameter_Name_5=Frequency
Parameter_Value_5=1
Parameter_Name_6=Phase
Parameter_Value_6=0
Parameter_Name_7=Samples
Parameter_Value_7=10
Parameter_Name_8=Offset
Parameter_Value_8=0
Parameter_Name_9=SampleTime
Parameter_Value_9=0
Parameter_Name_10=VectorParams1D
Parameter_Value_10=on
NumberOfInputSignals=0
NumberOfOutputSignals=1
NumberOfBlocks=0

