version: 2.1.0

test-unit-information:
  caption: Test Unit
  description: Test Unit
test-unit-implementation:
  - source-file-path: TestEnvironment.vtesttree.yaml
  - source-file-path: GeneralTest_Display.can
  - source-file-path: GeneralTests_Engine1.can
  - source-file-path: GeneralTests_Engine2.can
  - source-file-path: Test_Light.can
  - source-file-path: Test_MessageCycleTime.can
