version: 2.2.0

test-tree:
  - test-fixture: Message Cycle Time
    description: Message Cycle Time
    elements:
      - capl-test-case: tcsMsgCycleTimes
        title: Message Cycle Time
  - test-fixture: General Tests
    description: General Tests
    elements:
      - capl-test-case: tcsDisplay
        title: Display
  - test-fixture: Engine
    description: Engine
    elements:
      - capl-test-case: tcsEngineTest1
        title: Engine Test 1
      - capl-test-case: tcsEngineTest2
        title: Engine Test 2
  - test-fixture: Light Tests
    description: Light Tests
    elements:
      - capl-test-case: tcsLightTest
        title: Hazard Light




        